### PR TITLE
Updated EntityFramework, scaffold database, and begin CRUD.

### PR DESCRIPTION
**Pull request by jpue314**
I updated Entity Framework, Updated the models and scaffolded the Database. 

The JobPostController CRUD need some work.

### CODE REVIEW

**Comment by mgzs2013** [comment]
Ima hit up this up when I get home

**Comment by jpue314** [comment]
CRUD operations are now operational and I added some null checks. 

I believe what's next is adding JWT authentication and that will need a separate branch.

Let me know what you guys think if it looks ready to merge.
@JMorris40204 @tgavrity @mgzs2013

**Review by JMorris40204 — APPROVED** [review]
Right now it's just your additions here so If they work, I say you're good to merge

**Review by mgzs2013 — APPROVED** [review]
The first pull request is granted!

**Review by mgzs2013 — APPROVED** [review]
The first pull request is granted!

**Pull request merged**
